import { StyleSheet } from 'react-native';

export const addMemberModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  kav: {
    flex: 1,
    width: '100%',
    justifyContent: 'flex-end',
  },
  kavDesktop: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 16,
    maxHeight: '92%',
  },
  sheetCompact: {
    height: undefined,
    maxHeight: 430,
  },
  formScroll: {
    flex: 1,
  },
  formContent: {
    paddingBottom: 28,
  },
  handle: {
    width: 36,
    height: 5,
    backgroundColor: '#D1D5DB',
    borderRadius: 99,
    alignSelf: 'center',
    marginBottom: 18,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 4,
  },
  sheetSub: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 16,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  relCard: {
    width: '46%',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  relOff: {
    opacity: 0.55,
  },
  relIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF',
    marginBottom: 8,
  },
  relIconWrapOff: {
    backgroundColor: '#F3F4F6',
  },
  relLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
  },
  relMuted: {
    marginTop: 4,
    fontSize: 10,
    color: '#9CA3AF',
  },
  cancelBtn: {
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
  },
  cancelTxt: {
    fontSize: 14,
    color: '#6B7280',
  },
  back: {
    marginBottom: 14,
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backTxt: {
    fontSize: 14,
    color: '#4F46E5',
    fontWeight: '600',
    marginLeft: 2,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 16,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#111827',
    backgroundColor: '#FFFFFF',
  },
  gRow: {
    flexDirection: 'row',
    gap: 12,
  },
  gPill: {
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  gIcon: {
    marginRight: 2,
  },
  gLabel: {
    fontSize: 14,
    color: '#94A3B8',
    fontWeight: '600',
  },
  addBtn: {
    marginTop: 24,
    marginBottom: 8,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#007AFF',
    alignItems: 'center',
  },
  addTxt: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '700',
  },
});
